# Generated by Django 3.0.3 on 2024-01-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Open', models.DecimalField(decimal_places=12, max_digits=38)),
                ('High', models.DecimalField(decimal_places=12, max_digits=38)),
                ('Low', models.DecimalField(decimal_places=12, max_digits=38)),
                ('Close', models.DecimalField(decimal_places=12, max_digits=38)),
                ('Volume', models.IntegerField()),
                ('Dividends', models.DecimalField(decimal_places=12, max_digits=38)),
                ('Stock_Splits', models.DecimalField(decimal_places=12, max_digits=38)),
                ('Company', models.CharField(max_length=200)),
            ],
        ),
    ]
