# Generated by Django 3.0.3 on 2024-01-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_data', '0003_userportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headlines', models.CharField(max_length=200)),
                ('Time', models.DateField()),
                ('Description', models.CharField(max_length=200)),
                ('Ticker', models.CharField(max_length=10)),
            ],
        ),
    ]
