# Generated by Django 3.0.3 on 2024-01-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_data', '0005_auto_20240106_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='userportfolio',
            name='Remark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userportfolio',
            name='TargetPrice',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=38),
        ),
    ]
